### ISSUE TITLE
Running newrelic_resque_agent on Heroku

### ISSUE THREAD

**Issue by jeromeboe** [railsware/newrelic_platform_plugins#46]
I followed the intructions in the README, but it doesn't seem to work.

1) I add the gem
2) I created the config/newrelic_plugin.yml file as follow : 

``` yaml
newrelic:
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  verbose: 0

agents:
  my_resque_agent_name:
    redis: <%= ENV["REDISCLOUD_URL"] %>
    namespace:
```

3) I added `resque_monitoring: newrelic_resque_agent run -c config/newrelic_plugin.yml` to my Procfile
4) I scaled my dynos

My `ENV['REDISCLOUD_URL']` looks like `redis://rediscloud:password@pub-redis-16503.eu-west-1-1.2.ec2.garantiadata.com:16503`, I'm using the rediscloud heroku adds-on and the database is not specified.

I've been waiting for a wile, but I don't find any resque monitoring on my newrelic interface (nothing in the plugin section).
